//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Monitor.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serial_Monitor.Languages.en_local", typeof(en_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About Serial Monitor.
        /// </summary>
        internal static string aboutApp {
            get {
                return ResourceManager.GetString("aboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Pr&amp;ogram.
        /// </summary>
        internal static string activeProgram {
            get {
                return ResourceManager.GetString("activeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        internal static string addCommand {
            get {
                return ResourceManager.GetString("addCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command After.
        /// </summary>
        internal static string addCommandAfter {
            get {
                return ResourceManager.GetString("addCommandAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add to Monitor.
        /// </summary>
        internal static string addMonitor {
            get {
                return ResourceManager.GetString("addMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Escape Characters.
        /// </summary>
        internal static string allowEscapeChars {
            get {
                return ResourceManager.GetString("allowEscapeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Array.
        /// </summary>
        internal static string array {
            get {
                return ResourceManager.GetString("array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Baud Rate.
        /// </summary>
        internal static string baudRate {
            get {
                return ResourceManager.GetString("baudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bit Toggler.
        /// </summary>
        internal static string bitToggler {
            get {
                return ResourceManager.GetString("bitToggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Address.
        /// </summary>
        internal static string changeAddress {
            get {
                return ResourceManager.GetString("changeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;Appearance.
        /// </summary>
        internal static string changeAppearance {
            get {
                return ResourceManager.GetString("changeAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Channel.
        /// </summary>
        internal static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chec&amp;ksum Calculator.
        /// </summary>
        internal static string checksumCalculator {
            get {
                return ResourceManager.GetString("checksumCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lear Selection.
        /// </summary>
        internal static string clearSelection {
            get {
                return ResourceManager.GetString("clearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Terminal.
        /// </summary>
        internal static string clearTerminal {
            get {
                return ResourceManager.GetString("clearTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string closeAll {
            get {
                return ResourceManager.GetString("closeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp;All Snapshots.
        /// </summary>
        internal static string closeAllSnapshot {
            get {
                return ResourceManager.GetString("closeAllSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close Snapshot.
        /// </summary>
        internal static string closeSnapshot {
            get {
                return ResourceManager.GetString("closeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Command Palette.
        /// </summary>
        internal static string commandPalette {
            get {
                return ResourceManager.GetString("commandPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Appearance.
        /// </summary>
        internal static string copyAppearance {
            get {
                return ResourceManager.GetString("copyAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy As &amp;Text.
        /// </summary>
        internal static string copyAsText {
            get {
                return ResourceManager.GetString("copyAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Formats.
        /// </summary>
        internal static string copyFormats {
            get {
                return ResourceManager.GetString("copyFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Names.
        /// </summary>
        internal static string copyNames {
            get {
                return ResourceManager.GetString("copyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;Special.
        /// </summary>
        internal static string copySpecial {
            get {
                return ResourceManager.GetString("copySpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Values.
        /// </summary>
        internal static string copyValues {
            get {
                return ResourceManager.GetString("copyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Data Bits.
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data &amp;Size.
        /// </summary>
        internal static string dataSize {
            get {
                return ResourceManager.GetString("dataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal &amp;Places.
        /// </summary>
        internal static string decimalPlaces {
            get {
                return ResourceManager.GetString("decimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manager.
        /// </summary>
        internal static string deviceManager {
            get {
                return ResourceManager.GetString("deviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;isable Selected.
        /// </summary>
        internal static string disableSelected {
            get {
                return ResourceManager.GetString("disableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc&amp;onnect.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Display.
        /// </summary>
        internal static string displayFormat {
            get {
                return ResourceManager.GetString("displayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enabled Selected.
        /// </summary>
        internal static string enableSelected {
            get {
                return ResourceManager.GetString("enableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Execute.
        /// </summary>
        internal static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string extensions {
            get {
                return ResourceManager.GetString("extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Flow Control.
        /// </summary>
        internal static string flowControl {
            get {
                return ResourceManager.GetString("flowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Signed.
        /// </summary>
        internal static string formatSigned {
            get {
                return ResourceManager.GetString("formatSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Global Variables.
        /// </summary>
        internal static string globalVariables {
            get {
                return ResourceManager.GetString("globalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go To.
        /// </summary>
        internal static string gotoMi {
            get {
                return ResourceManager.GetString("gotoMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Input Format.
        /// </summary>
        internal static string inputFormat {
            get {
                return ResourceManager.GetString("inputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Keypad.
        /// </summary>
        internal static string keypad {
            get {
                return ResourceManager.GetString("keypad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Local Variables.
        /// </summary>
        internal static string localVariables {
            get {
                return ResourceManager.GetString("localVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Editor.
        /// </summary>
        internal static string lockEditor {
            get {
                return ResourceManager.GetString("lockEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master View.
        /// </summary>
        internal static string masterView {
            get {
                return ResourceManager.GetString("masterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modbus.
        /// </summary>
        internal static string modbus {
            get {
                return ResourceManager.GetString("modbus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Format.
        /// </summary>
        internal static string modbusAddressFormat {
            get {
                return ResourceManager.GetString("modbusAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Coils.
        /// </summary>
        internal static string modbusCoils {
            get {
                return ResourceManager.GetString("modbusCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Discrete Inputs.
        /// </summary>
        internal static string modbusDiscreteInputs {
            get {
                return ResourceManager.GetString("modbusDiscreteInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Holding Registers.
        /// </summary>
        internal static string modbusHoldingRegisters {
            get {
                return ResourceManager.GetString("modbusHoldingRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &amp;Registers.
        /// </summary>
        internal static string modbusInputRegisters {
            get {
                return ResourceManager.GetString("modbusInputRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus Master.
        /// </summary>
        internal static string modbusMaster {
            get {
                return ResourceManager.GetString("modbusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus &amp;Query Editor.
        /// </summary>
        internal static string modbusQueryEditor {
            get {
                return ResourceManager.GetString("modbusQueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus &amp;Registers.
        /// </summary>
        internal static string modbusRegisters {
            get {
                return ResourceManager.GetString("modbusRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write &amp;Coil.
        /// </summary>
        internal static string modbusWriteCoil {
            get {
                return ResourceManager.GetString("modbusWriteCoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Multiple Coils.
        /// </summary>
        internal static string modbusWriteMultipleCoils {
            get {
                return ResourceManager.GetString("modbusWriteMultipleCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Multiple Registers.
        /// </summary>
        internal static string modbusWriteMultipleRegisters {
            get {
                return ResourceManager.GetString("modbusWriteMultipleRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write &amp;Register.
        /// </summary>
        internal static string modbusWriteRegister {
            get {
                return ResourceManager.GetString("modbusWriteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Register &amp;Mask.
        /// </summary>
        internal static string modbusWriteRegisterMask {
            get {
                return ResourceManager.GetString("modbusWriteRegisterMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monitor.
        /// </summary>
        internal static string monitor {
            get {
                return ResourceManager.GetString("monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Down.
        /// </summary>
        internal static string moveDown {
            get {
                return ResourceManager.GetString("moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Up.
        /// </summary>
        internal static string moveUp {
            get {
                return ResourceManager.GetString("moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Channel.
        /// </summary>
        internal static string newChannel {
            get {
                return ResourceManager.GetString("newChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Program.
        /// </summary>
        internal static string newProgram {
            get {
                return ResourceManager.GetString("newProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Unit.
        /// </summary>
        internal static string newUnit {
            get {
                return ResourceManager.GetString("newUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;View.
        /// </summary>
        internal static string newView {
            get {
                return ResourceManager.GetString("newView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        internal static string openFileLocation {
            get {
                return ResourceManager.GetString("openFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in New Terminal.
        /// </summary>
        internal static string openInTerminal {
            get {
                return ResourceManager.GetString("openInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Log.
        /// </summary>
        internal static string openLog {
            get {
                return ResourceManager.GetString("openLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Copy of Log in Excel.
        /// </summary>
        internal static string openLogExcel {
            get {
                return ResourceManager.GetString("openLogExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Location.
        /// </summary>
        internal static string openLogLocation {
            get {
                return ResourceManager.GetString("openLogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output Format.
        /// </summary>
        internal static string outputFormat {
            get {
                return ResourceManager.GetString("outputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output in Termina&amp;l.
        /// </summary>
        internal static string outputInTerminal {
            get {
                return ResourceManager.GetString("outputInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;arity.
        /// </summary>
        internal static string partity {
            get {
                return ResourceManager.GetString("partity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Program.
        /// </summary>
        internal static string pauseProgram {
            get {
                return ResourceManager.GetString("pauseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view.
        /// </summary>
        internal static string printPreview {
            get {
                return ResourceManager.GetString("printPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Program Properties.
        /// </summary>
        internal static string programProperties {
            get {
                return ResourceManager.GetString("programProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Query.
        /// </summary>
        internal static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quick Converter.
        /// </summary>
        internal static string quickConverter {
            get {
                return ResourceManager.GetString("quickConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        internal static string recentProjects {
            get {
                return ResourceManager.GetString("recentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Channel.
        /// </summary>
        internal static string removeChannel {
            get {
                return ResourceManager.GetString("removeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Monitor.
        /// </summary>
        internal static string removeMonitor {
            get {
                return ResourceManager.GetString("removeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remo&amp;ve Program.
        /// </summary>
        internal static string removeProgram {
            get {
                return ResourceManager.GetString("removeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Selected.
        /// </summary>
        internal static string removeSelected {
            get {
                return ResourceManager.GetString("removeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;move Unit.
        /// </summary>
        internal static string removeUnit {
            get {
                return ResourceManager.GetString("removeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;ename Channel.
        /// </summary>
        internal static string renameChannel {
            get {
                return ResourceManager.GetString("renameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;ename Unit.
        /// </summary>
        internal static string renameUnit {
            get {
                return ResourceManager.GetString("renameUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset Appearance.
        /// </summary>
        internal static string resetAppearance {
            get {
                return ResourceManager.GetString("resetAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Counters.
        /// </summary>
        internal static string resetCounters {
            get {
                return ResourceManager.GetString("resetCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;un Progra&amp;m.
        /// </summary>
        internal static string runProgram {
            get {
                return ResourceManager.GetString("runProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Program from Start.
        /// </summary>
        internal static string runProgramStart {
            get {
                return ResourceManager.GetString("runProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        internal static string saveAs {
            get {
                return ResourceManager.GetString("saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Log.
        /// </summary>
        internal static string saveLog {
            get {
                return ResourceManager.GetString("saveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Ports.
        /// </summary>
        internal static string scanPorts {
            get {
                return ResourceManager.GetString("scanPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search Registers.
        /// </summary>
        internal static string searchRegisters {
            get {
                return ResourceManager.GetString("searchRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Invert.
        /// </summary>
        internal static string selectInvert {
            get {
                return ResourceManager.GetString("selectInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection to Snapshot.
        /// </summary>
        internal static string selectionToSnapshot {
            get {
                return ResourceManager.GetString("selectionToSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Matching Formats.
        /// </summary>
        internal static string selectMatchingFormats {
            get {
                return ResourceManager.GetString("selectMatchingFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Matching Names.
        /// </summary>
        internal static string selectMatchingNames {
            get {
                return ResourceManager.GetString("selectMatchingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Matching Values.
        /// </summary>
        internal static string selectMatchingValues {
            get {
                return ResourceManager.GetString("selectMatchingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Special.
        /// </summary>
        internal static string selectSpecial {
            get {
                return ResourceManager.GetString("selectSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        internal static string sendFile {
            get {
                return ResourceManager.GetString("sendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on Change.
        /// </summary>
        internal static string sendOnChange {
            get {
                return ResourceManager.GetString("sendOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set as Active Program.
        /// </summary>
        internal static string setAsActiveProgram {
            get {
                return ResourceManager.GetString("setAsActiveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Formats to Modbus ASCII.
        /// </summary>
        internal static string setFormatsToModbusASCII {
            get {
                return ResourceManager.GetString("setFormatsToModbusASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Formats to Modbus RTU.
        /// </summary>
        internal static string setFormatsToModbusRTU {
            get {
                return ResourceManager.GetString("setFormatsToModbusRTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Step Cursor.
        /// </summary>
        internal static string setStepCursor {
            get {
                return ResourceManager.GetString("setStepCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Formats.
        /// </summary>
        internal static string showFormats {
            get {
                return ResourceManager.GetString("showFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Last Updated Time.
        /// </summary>
        internal static string showLastUpdatedTime {
            get {
                return ResourceManager.GetString("showLastUpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Source.
        /// </summary>
        internal static string showSource {
            get {
                return ResourceManager.GetString("showSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Units.
        /// </summary>
        internal static string showUnits {
            get {
                return ResourceManager.GetString("showUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si&amp;gned.
        /// </summary>
        internal static string signed {
            get {
                return ResourceManager.GetString("signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave Manager.
        /// </summary>
        internal static string slaveManager {
            get {
                return ResourceManager.GetString("slaveManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        internal static string snapshots {
            get {
                return ResourceManager.GetString("snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snapshot Selection.
        /// </summary>
        internal static string snapshotSelection {
            get {
                return ResourceManager.GetString("snapshotSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot View.
        /// </summary>
        internal static string snapshotView {
            get {
                return ResourceManager.GetString("snapshotView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Logging.
        /// </summary>
        internal static string startLogging {
            get {
                return ResourceManager.GetString("startLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;tep Program.
        /// </summary>
        internal static string stepProgram {
            get {
                return ResourceManager.GetString("stepProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top Bits.
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto&amp;p Logging.
        /// </summary>
        internal static string stopLogging {
            get {
                return ResourceManager.GetString("stopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top Program.
        /// </summary>
        internal static string stopProgram {
            get {
                return ResourceManager.GetString("stopProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Switch Channel.
        /// </summary>
        internal static string switchChannel {
            get {
                return ResourceManager.GetString("switchChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text Comparator.
        /// </summary>
        internal static string textCompare {
            get {
                return ResourceManager.GetString("textCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Formatting.
        /// </summary>
        internal static string textFormatting {
            get {
                return ResourceManager.GetString("textFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tile Windows.
        /// </summary>
        internal static string tileWindows {
            get {
                return ResourceManager.GetString("tileWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toggle.
        /// </summary>
        internal static string toggle {
            get {
                return ResourceManager.GetString("toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toggle Selected.
        /// </summary>
        internal static string toggleSelected {
            get {
                return ResourceManager.GetString("toggleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Top Most.
        /// </summary>
        internal static string topMost {
            get {
                return ResourceManager.GetString("topMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unsigned.
        /// </summary>
        internal static string unsigned {
            get {
                return ResourceManager.GetString("unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Program.
        /// </summary>
        internal static string untitledProgram {
            get {
                return ResourceManager.GetString("untitledProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Variables.
        /// </summary>
        internal static string variables {
            get {
                return ResourceManager.GetString("variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Only.
        /// </summary>
        internal static string viewDataOnly {
            get {
                return ResourceManager.GetString("viewDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Stamps.
        /// </summary>
        internal static string viewDateStamps {
            get {
                return ResourceManager.GetString("viewDateStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Stamps.
        /// </summary>
        internal static string viewDateTimeStamps {
            get {
                return ResourceManager.GetString("viewDateTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamps.
        /// </summary>
        internal static string viewTimeStamps {
            get {
                return ResourceManager.GetString("viewTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Manager.
        /// </summary>
        internal static string windowManager {
            get {
                return ResourceManager.GetString("windowManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Word Order.
        /// </summary>
        internal static string wordOrder {
            get {
                return ResourceManager.GetString("wordOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zoom.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
