//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Monitor.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serial_Monitor.Languages.pl_local", typeof(pl_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny program.
        /// </summary>
        internal static string activeProgram {
            get {
                return ResourceManager.GetString("activeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj polecenie.
        /// </summary>
        internal static string addCommand {
            get {
                return ResourceManager.GetString("addCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj polecenie po.
        /// </summary>
        internal static string addCommandAfter {
            get {
                return ResourceManager.GetString("addCommandAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybkość transmisji.
        /// </summary>
        internal static string baudRate {
            get {
                return ResourceManager.GetString("baudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącznik bitowy.
        /// </summary>
        internal static string bitToggler {
            get {
                return ResourceManager.GetString("bitToggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanał.
        /// </summary>
        internal static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanały.
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść terminal.
        /// </summary>
        internal static string clearTerminal {
            get {
                return ResourceManager.GetString("clearTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij wszystko.
        /// </summary>
        internal static string closeAll {
            get {
                return ResourceManager.GetString("closeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paleta poleceń.
        /// </summary>
        internal static string commandPalette {
            get {
                return ResourceManager.GetString("commandPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączyć.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj styl.
        /// </summary>
        internal static string copyAppearance {
            get {
                return ResourceManager.GetString("copyAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj formaty.
        /// </summary>
        internal static string copyFormats {
            get {
                return ResourceManager.GetString("copyFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj nazwy.
        /// </summary>
        internal static string copyNames {
            get {
                return ResourceManager.GetString("copyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopia specjalna.
        /// </summary>
        internal static string copySpecial {
            get {
                return ResourceManager.GetString("copySpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj wartości.
        /// </summary>
        internal static string copyValues {
            get {
                return ResourceManager.GetString("copyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytnij.
        /// </summary>
        internal static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bity danych.
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menadżer urządzeń.
        /// </summary>
        internal static string deviceManager {
            get {
                return ResourceManager.GetString("deviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz wybrane.
        /// </summary>
        internal static string disableSelected {
            get {
                return ResourceManager.GetString("disableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozłączyć się.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włączone Wybrane.
        /// </summary>
        internal static string enableSelected {
            get {
                return ResourceManager.GetString("enableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozszerzenia.
        /// </summary>
        internal static string extensions {
            get {
                return ResourceManager.GetString("extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola przepływu.
        /// </summary>
        internal static string flowControl {
            get {
                return ResourceManager.GetString("flowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełny ekran.
        /// </summary>
        internal static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format wejściowy.
        /// </summary>
        internal static string inputFormat {
            get {
                return ResourceManager.GetString("inputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klawiatura.
        /// </summary>
        internal static string keypad {
            get {
                return ResourceManager.GetString("keypad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok mistrzowski.
        /// </summary>
        internal static string masterView {
            get {
                return ResourceManager.GetString("masterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistrz Modbusa.
        /// </summary>
        internal static string modbusMaster {
            get {
                return ResourceManager.GetString("modbusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestry Modbus.
        /// </summary>
        internal static string modbusRegisters {
            get {
                return ResourceManager.GetString("modbusRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string monitor {
            get {
                return ResourceManager.GetString("monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padnij.
        /// </summary>
        internal static string moveDown {
            get {
                return ResourceManager.GetString("moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podnieść.
        /// </summary>
        internal static string moveUp {
            get {
                return ResourceManager.GetString("moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy kanał.
        /// </summary>
        internal static string newChannel {
            get {
                return ResourceManager.GetString("newChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy program.
        /// </summary>
        internal static string newProgram {
            get {
                return ResourceManager.GetString("newProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy widok.
        /// </summary>
        internal static string newView {
            get {
                return ResourceManager.GetString("newView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz lokalizację pliku.
        /// </summary>
        internal static string openFileLocation {
            get {
                return ResourceManager.GetString("openFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz w nowym terminalu.
        /// </summary>
        internal static string openInTerminal {
            get {
                return ResourceManager.GetString("openInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format wyjściowy.
        /// </summary>
        internal static string outputFormat {
            get {
                return ResourceManager.GetString("outputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane wyjściowe w terminalu.
        /// </summary>
        internal static string outputInTerminal {
            get {
                return ResourceManager.GetString("outputInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parytet.
        /// </summary>
        internal static string partity {
            get {
                return ResourceManager.GetString("partity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstrzymaj program.
        /// </summary>
        internal static string pauseProgram {
            get {
                return ResourceManager.GetString("pauseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydrukować.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd wydruku.
        /// </summary>
        internal static string printPreview {
            get {
                return ResourceManager.GetString("printPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwości programu.
        /// </summary>
        internal static string programProperties {
            get {
                return ResourceManager.GetString("programProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieruchomości.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie projekty.
        /// </summary>
        internal static string recentProjects {
            get {
                return ResourceManager.GetString("recentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń kanał.
        /// </summary>
        internal static string removeChannel {
            get {
                return ResourceManager.GetString("removeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń program.
        /// </summary>
        internal static string removeProgram {
            get {
                return ResourceManager.GetString("removeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wybrane.
        /// </summary>
        internal static string removeSelected {
            get {
                return ResourceManager.GetString("removeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień nazwę kanału.
        /// </summary>
        internal static string renameChannel {
            get {
                return ResourceManager.GetString("renameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetowanie.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zresetuj liczniki.
        /// </summary>
        internal static string resetCounters {
            get {
                return ResourceManager.GetString("resetCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom program.
        /// </summary>
        internal static string runProgram {
            get {
                return ResourceManager.GetString("runProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom program od początku.
        /// </summary>
        internal static string runProgramStart {
            get {
                return ResourceManager.GetString("runProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz jako.
        /// </summary>
        internal static string saveAs {
            get {
                return ResourceManager.GetString("saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystko.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz opcję Odwróć.
        /// </summary>
        internal static string selectInvert {
            get {
                return ResourceManager.GetString("selectInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz opcję Dopasowane formaty.
        /// </summary>
        internal static string selectMatchingFormats {
            get {
                return ResourceManager.GetString("selectMatchingFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz Pasujące nazwy.
        /// </summary>
        internal static string selectMatchingNames {
            get {
                return ResourceManager.GetString("selectMatchingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz opcję Pasujące wartości.
        /// </summary>
        internal static string selectMatchingValues {
            get {
                return ResourceManager.GetString("selectMatchingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz opcję Specjalne.
        /// </summary>
        internal static string selectSpecial {
            get {
                return ResourceManager.GetString("selectSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw kursor krokowy.
        /// </summary>
        internal static string setStepCursor {
            get {
                return ResourceManager.GetString("setStepCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż formaty.
        /// </summary>
        internal static string showFormats {
            get {
                return ResourceManager.GetString("showFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż źródło.
        /// </summary>
        internal static string showSource {
            get {
                return ResourceManager.GetString("showSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż jednostki.
        /// </summary>
        internal static string showUnits {
            get {
                return ResourceManager.GetString("showUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok migawki.
        /// </summary>
        internal static string snapshotView {
            get {
                return ResourceManager.GetString("snapshotView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program krokowy.
        /// </summary>
        internal static string stepProgram {
            get {
                return ResourceManager.GetString("stepProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj bity.
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj program.
        /// </summary>
        internal static string stopProgram {
            get {
                return ResourceManager.GetString("stopProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącz kanał.
        /// </summary>
        internal static string switchChannel {
            get {
                return ResourceManager.GetString("switchChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porównanie tekstu.
        /// </summary>
        internal static string textCompare {
            get {
                return ResourceManager.GetString("textCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatowanie tekstu.
        /// </summary>
        internal static string textFormatting {
            get {
                return ResourceManager.GetString("textFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącz wybrane.
        /// </summary>
        internal static string toggleSelected {
            get {
                return ResourceManager.GetString("toggleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narzędzia.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najwyżej.
        /// </summary>
        internal static string topMost {
            get {
                return ResourceManager.GetString("topMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy projekt.
        /// </summary>
        internal static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program bez nazwy.
        /// </summary>
        internal static string untitledProgram {
            get {
                return ResourceManager.GetString("untitledProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmienne.
        /// </summary>
        internal static string variables {
            get {
                return ResourceManager.GetString("variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko dane.
        /// </summary>
        internal static string viewDataOnly {
            get {
                return ResourceManager.GetString("viewDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczki daty.
        /// </summary>
        internal static string viewDateStamps {
            get {
                return ResourceManager.GetString("viewDateStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczki daty/godziny.
        /// </summary>
        internal static string viewDateTimeStamps {
            get {
                return ResourceManager.GetString("viewDateTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczki czasu.
        /// </summary>
        internal static string viewTimeStamps {
            get {
                return ResourceManager.GetString("viewTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okno.
        /// </summary>
        internal static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer okien.
        /// </summary>
        internal static string windowManager {
            get {
                return ResourceManager.GetString("windowManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiększenie.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
