//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Monitor.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serial_Monitor.Languages.pl_local", typeof(pl_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nowy.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;O programie Serial Monitor.
        /// </summary>
        internal static string aboutApp {
            get {
                return ResourceManager.GetString("aboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny pr&amp;ogram.
        /// </summary>
        internal static string activeProgram {
            get {
                return ResourceManager.GetString("activeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj polecenie.
        /// </summary>
        internal static string addCommand {
            get {
                return ResourceManager.GetString("addCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj polecenie po.
        /// </summary>
        internal static string addCommandAfter {
            get {
                return ResourceManager.GetString("addCommandAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dodaj do monitora.
        /// </summary>
        internal static string addMonitor {
            get {
                return ResourceManager.GetString("addMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zezwalaj na znaki ucieczki.
        /// </summary>
        internal static string allowEscapeChars {
            get {
                return ResourceManager.GetString("allowEscapeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tablica.
        /// </summary>
        internal static string array {
            get {
                return ResourceManager.GetString("array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Szybkość transmisji.
        /// </summary>
        internal static string baudRate {
            get {
                return ResourceManager.GetString("baudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącznik &amp;bitów.
        /// </summary>
        internal static string bitToggler {
            get {
                return ResourceManager.GetString("bitToggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień adres.
        /// </summary>
        internal static string changeAddress {
            get {
                return ResourceManager.GetString("changeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień &amp;wygląd.
        /// </summary>
        internal static string changeAppearance {
            get {
                return ResourceManager.GetString("changeAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kanał.
        /// </summary>
        internal static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor kanału.
        /// </summary>
        internal static string channelColor {
            get {
                return ResourceManager.GetString("channelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanały.
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulator sumy &amp;kontrolnej.
        /// </summary>
        internal static string checksumCalculator {
            get {
                return ResourceManager.GetString("checksumCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wy&amp;czyść zaznaczenie.
        /// </summary>
        internal static string clearSelection {
            get {
                return ResourceManager.GetString("clearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść terminal.
        /// </summary>
        internal static string clearTerminal {
            get {
                return ResourceManager.GetString("clearTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij wszystkie.
        /// </summary>
        internal static string closeAll {
            get {
                return ResourceManager.GetString("closeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij &amp;wszystkie migawki.
        /// </summary>
        internal static string closeAllSnapshot {
            get {
                return ResourceManager.GetString("closeAllSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij &amp;migawkę.
        /// </summary>
        internal static string closeSnapshot {
            get {
                return ResourceManager.GetString("closeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paleta poleceń.
        /// </summary>
        internal static string commandPalette {
            get {
                return ResourceManager.GetString("commandPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porównaj od.
        /// </summary>
        internal static string compareFrom {
            get {
                return ResourceManager.GetString("compareFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porównaj do.
        /// </summary>
        internal static string compareTo {
            get {
                return ResourceManager.GetString("compareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Połącz.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kopiuj.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj wygląd.
        /// </summary>
        internal static string copyAppearance {
            get {
                return ResourceManager.GetString("copyAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj jako &amp;tekst.
        /// </summary>
        internal static string copyAsText {
            get {
                return ResourceManager.GetString("copyAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj formaty.
        /// </summary>
        internal static string copyFormats {
            get {
                return ResourceManager.GetString("copyFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj nazwy.
        /// </summary>
        internal static string copyNames {
            get {
                return ResourceManager.GetString("copyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj &amp;specjalnie.
        /// </summary>
        internal static string copySpecial {
            get {
                return ResourceManager.GetString("copySpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj wartości.
        /// </summary>
        internal static string copyValues {
            get {
                return ResourceManager.GetString("copyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wy&amp;tnij.
        /// </summary>
        internal static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bity danych.
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar &amp;danych.
        /// </summary>
        internal static string dataSize {
            get {
                return ResourceManager.GetString("dataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsca &amp;dziesiętne.
        /// </summary>
        internal static string decimalPlaces {
            get {
                return ResourceManager.GetString("decimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Usuń.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer urządzeń.
        /// </summary>
        internal static string deviceManager {
            get {
                return ResourceManager.GetString("deviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłą&amp;cz zaznaczone.
        /// </summary>
        internal static string disableSelected {
            get {
                return ResourceManager.GetString("disableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roz&amp;łącz.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wyświetlanie.
        /// </summary>
        internal static string displayFormat {
            get {
                return ResourceManager.GetString("displayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edycja.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Włącz zaznaczone.
        /// </summary>
        internal static string enableSelected {
            get {
                return ResourceManager.GetString("enableSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wykonaj.
        /// </summary>
        internal static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za&amp;kończ.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Eksportuj.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozszerzenia.
        /// </summary>
        internal static string extensions {
            get {
                return ResourceManager.GetString("extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plik.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kontrola przepływu.
        /// </summary>
        internal static string flowControl {
            get {
                return ResourceManager.GetString("flowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ze znakiem.
        /// </summary>
        internal static string formatSigned {
            get {
                return ResourceManager.GetString("formatSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełny ekran.
        /// </summary>
        internal static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zmienne globalne.
        /// </summary>
        internal static string globalVariables {
            get {
                return ResourceManager.GetString("globalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Przejdź do.
        /// </summary>
        internal static string gotoMi {
            get {
                return ResourceManager.GetString("gotoMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format wejściowy.
        /// </summary>
        internal static string inputFormat {
            get {
                return ResourceManager.GetString("inputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Klawiatura.
        /// </summary>
        internal static string keypad {
            get {
                return ResourceManager.GetString("keypad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zmienne lokalne.
        /// </summary>
        internal static string localVariables {
            get {
                return ResourceManager.GetString("localVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokuj edytor.
        /// </summary>
        internal static string lockEditor {
            get {
                return ResourceManager.GetString("lockEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok główny.
        /// </summary>
        internal static string masterView {
            get {
                return ResourceManager.GetString("masterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modbus.
        /// </summary>
        internal static string modbus {
            get {
                return ResourceManager.GetString("modbus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format adresu.
        /// </summary>
        internal static string modbusAddressFormat {
            get {
                return ResourceManager.GetString("modbusAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cewki.
        /// </summary>
        internal static string modbusCoils {
            get {
                return ResourceManager.GetString("modbusCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wejścia dyskretne.
        /// </summary>
        internal static string modbusDiscreteInputs {
            get {
                return ResourceManager.GetString("modbusDiscreteInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rejestry Holding.
        /// </summary>
        internal static string modbusHoldingRegisters {
            get {
                return ResourceManager.GetString("modbusHoldingRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestry &amp;wejściowe.
        /// </summary>
        internal static string modbusInputRegisters {
            get {
                return ResourceManager.GetString("modbusInputRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Modbus.
        /// </summary>
        internal static string modbusMaster {
            get {
                return ResourceManager.GetString("modbusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytor &amp;zapytań Modbus.
        /// </summary>
        internal static string modbusQueryEditor {
            get {
                return ResourceManager.GetString("modbusQueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rejestry Modbus.
        /// </summary>
        internal static string modbusRegisters {
            get {
                return ResourceManager.GetString("modbusRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz &amp;cewkę.
        /// </summary>
        internal static string modbusWriteCoil {
            get {
                return ResourceManager.GetString("modbusWriteCoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz wiele cewek.
        /// </summary>
        internal static string modbusWriteMultipleCoils {
            get {
                return ResourceManager.GetString("modbusWriteMultipleCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz wiele rejestrów.
        /// </summary>
        internal static string modbusWriteMultipleRegisters {
            get {
                return ResourceManager.GetString("modbusWriteMultipleRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz &amp;rejestr.
        /// </summary>
        internal static string modbusWriteRegister {
            get {
                return ResourceManager.GetString("modbusWriteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz &amp;maskę rejestru.
        /// </summary>
        internal static string modbusWriteRegisterMask {
            get {
                return ResourceManager.GetString("modbusWriteRegisterMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monitor.
        /// </summary>
        internal static string monitor {
            get {
                return ResourceManager.GetString("monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesuń w &amp;dół.
        /// </summary>
        internal static string moveDown {
            get {
                return ResourceManager.GetString("moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesuń w &amp;górę.
        /// </summary>
        internal static string moveUp {
            get {
                return ResourceManager.GetString("moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nowy kanał.
        /// </summary>
        internal static string newChannel {
            get {
                return ResourceManager.GetString("newChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nowy program.
        /// </summary>
        internal static string newProgram {
            get {
                return ResourceManager.GetString("newProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nowa jednostka.
        /// </summary>
        internal static string newUnit {
            get {
                return ResourceManager.GetString("newUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy &amp;widok.
        /// </summary>
        internal static string newView {
            get {
                return ResourceManager.GetString("newView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string noEndOfLineFormat {
            get {
                return ResourceManager.GetString("noEndOfLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Otwórz.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz lokalizację pliku.
        /// </summary>
        internal static string openFileLocation {
            get {
                return ResourceManager.GetString("openFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz w nowym terminalu.
        /// </summary>
        internal static string openInTerminal {
            get {
                return ResourceManager.GetString("openInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz &amp;dziennik.
        /// </summary>
        internal static string openLog {
            get {
                return ResourceManager.GetString("openLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz kopię dziennika w Excelu.
        /// </summary>
        internal static string openLogExcel {
            get {
                return ResourceManager.GetString("openLogExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz lokalizację dziennika.
        /// </summary>
        internal static string openLogLocation {
            get {
                return ResourceManager.GetString("openLogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Opcje.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format wyjściowy.
        /// </summary>
        internal static string outputFormat {
            get {
                return ResourceManager.GetString("outputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście w termina&amp;lu.
        /// </summary>
        internal static string outputInTerminal {
            get {
                return ResourceManager.GetString("outputInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;arity.
        /// </summary>
        internal static string partity {
            get {
                return ResourceManager.GetString("partity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wklej.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauza.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstrzymaj program.
        /// </summary>
        internal static string pauseProgram {
            get {
                return ResourceManager.GetString("pauseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Drukuj.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd wydruku.
        /// </summary>
        internal static string printPreview {
            get {
                return ResourceManager.GetString("printPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Właściwości programu.
        /// </summary>
        internal static string programProperties {
            get {
                return ResourceManager.GetString("programProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Właściwości.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zapytanie.
        /// </summary>
        internal static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Szybki konwerter.
        /// </summary>
        internal static string quickConverter {
            get {
                return ResourceManager.GetString("quickConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie projekty.
        /// </summary>
        internal static string recentProjects {
            get {
                return ResourceManager.GetString("recentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ponów.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Usuń kanał.
        /// </summary>
        internal static string removeChannel {
            get {
                return ResourceManager.GetString("removeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Usuń z monitora.
        /// </summary>
        internal static string removeMonitor {
            get {
                return ResourceManager.GetString("removeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń pr&amp;ogram.
        /// </summary>
        internal static string removeProgram {
            get {
                return ResourceManager.GetString("removeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Usuń zaznaczone.
        /// </summary>
        internal static string removeSelected {
            get {
                return ResourceManager.GetString("removeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń jednos&amp;tkę.
        /// </summary>
        internal static string removeUnit {
            get {
                return ResourceManager.GetString("removeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień nazwę.
        /// </summary>
        internal static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień &amp;nazwę kanału.
        /// </summary>
        internal static string renameChannel {
            get {
                return ResourceManager.GetString("renameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień n&amp;azwę jednostki.
        /// </summary>
        internal static string renameUnit {
            get {
                return ResourceManager.GetString("renameUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resetuj.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resetuj wygląd.
        /// </summary>
        internal static string resetAppearance {
            get {
                return ResourceManager.GetString("resetAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj liczniki.
        /// </summary>
        internal static string resetCounters {
            get {
                return ResourceManager.GetString("resetCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom p&amp;rogram.
        /// </summary>
        internal static string runProgram {
            get {
                return ResourceManager.GetString("runProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom program od początku.
        /// </summary>
        internal static string runProgramStart {
            get {
                return ResourceManager.GetString("runProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zapisz.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz &amp;jako.
        /// </summary>
        internal static string saveAs {
            get {
                return ResourceManager.GetString("saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zapisz dziennik.
        /// </summary>
        internal static string saveLog {
            get {
                return ResourceManager.GetString("saveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skanuj porty.
        /// </summary>
        internal static string scanPorts {
            get {
                return ResourceManager.GetString("scanPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Szukaj rejestrów.
        /// </summary>
        internal static string searchRegisters {
            get {
                return ResourceManager.GetString("searchRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz wszystko.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odwróć zaznaczenie.
        /// </summary>
        internal static string selectInvert {
            get {
                return ResourceManager.GetString("selectInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zaznaczenie do migawki.
        /// </summary>
        internal static string selectionToSnapshot {
            get {
                return ResourceManager.GetString("selectionToSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz pasujące formaty.
        /// </summary>
        internal static string selectMatchingFormats {
            get {
                return ResourceManager.GetString("selectMatchingFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz pasujące nazwy.
        /// </summary>
        internal static string selectMatchingNames {
            get {
                return ResourceManager.GetString("selectMatchingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz pasujące wartości.
        /// </summary>
        internal static string selectMatchingValues {
            get {
                return ResourceManager.GetString("selectMatchingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz specjalne.
        /// </summary>
        internal static string selectSpecial {
            get {
                return ResourceManager.GetString("selectSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij plik.
        /// </summary>
        internal static string sendFile {
            get {
                return ResourceManager.GetString("sendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij przy zmianie.
        /// </summary>
        internal static string sendOnChange {
            get {
                return ResourceManager.GetString("sendOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ustaw jako aktywny program.
        /// </summary>
        internal static string setAsActiveProgram {
            get {
                return ResourceManager.GetString("setAsActiveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw formaty na Modbus ASCII.
        /// </summary>
        internal static string setFormatsToModbusASCII {
            get {
                return ResourceManager.GetString("setFormatsToModbusASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw formaty na Modbus RTU.
        /// </summary>
        internal static string setFormatsToModbusRTU {
            get {
                return ResourceManager.GetString("setFormatsToModbusRTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw kursor kroku.
        /// </summary>
        internal static string setStepCursor {
            get {
                return ResourceManager.GetString("setStepCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż &amp;formaty.
        /// </summary>
        internal static string showFormats {
            get {
                return ResourceManager.GetString("showFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż czas ostatniej aktualizacji.
        /// </summary>
        internal static string showLastUpdatedTime {
            get {
                return ResourceManager.GetString("showLastUpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż źródło.
        /// </summary>
        internal static string showSource {
            get {
                return ResourceManager.GetString("showSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż &amp;jednostki.
        /// </summary>
        internal static string showUnits {
            get {
                return ResourceManager.GetString("showUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ze znakiem.
        /// </summary>
        internal static string signed {
            get {
                return ResourceManager.GetString("signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer slave.
        /// </summary>
        internal static string slaveManager {
            get {
                return ResourceManager.GetString("slaveManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migawki.
        /// </summary>
        internal static string snapshots {
            get {
                return ResourceManager.GetString("snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Migawka zaznaczenia.
        /// </summary>
        internal static string snapshotSelection {
            get {
                return ResourceManager.GetString("snapshotSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok migawki.
        /// </summary>
        internal static string snapshotView {
            get {
                return ResourceManager.GetString("snapshotView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij logowanie.
        /// </summary>
        internal static string startLogging {
            get {
                return ResourceManager.GetString("startLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krok programu.
        /// </summary>
        internal static string stepProgram {
            get {
                return ResourceManager.GetString("stepProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top bits.
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj logowanie.
        /// </summary>
        internal static string stopLogging {
            get {
                return ResourceManager.GetString("stopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj program.
        /// </summary>
        internal static string stopProgram {
            get {
                return ResourceManager.GetString("stopProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Przełącz kanał.
        /// </summary>
        internal static string switchChannel {
            get {
                return ResourceManager.GetString("switchChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Porównywarka tekstu.
        /// </summary>
        internal static string textCompare {
            get {
                return ResourceManager.GetString("textCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatowanie tekstu.
        /// </summary>
        internal static string textFormatting {
            get {
                return ResourceManager.GetString("textFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kaskada okien.
        /// </summary>
        internal static string tileWindows {
            get {
                return ResourceManager.GetString("tileWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Przełącz.
        /// </summary>
        internal static string toggle {
            get {
                return ResourceManager.GetString("toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Przełącz zaznaczone.
        /// </summary>
        internal static string toggleSelected {
            get {
                return ResourceManager.GetString("toggleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Narzędzia.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zawsze na wierzchu.
        /// </summary>
        internal static string topMost {
            get {
                return ResourceManager.GetString("topMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cofnij.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bez znaku.
        /// </summary>
        internal static string unsigned {
            get {
                return ResourceManager.GetString("unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez tytułu.
        /// </summary>
        internal static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program bez tytułu.
        /// </summary>
        internal static string untitledProgram {
            get {
                return ResourceManager.GetString("untitledProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zmienne.
        /// </summary>
        internal static string variables {
            get {
                return ResourceManager.GetString("variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Widok.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko dane.
        /// </summary>
        internal static string viewDataOnly {
            get {
                return ResourceManager.GetString("viewDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczniki daty.
        /// </summary>
        internal static string viewDateStamps {
            get {
                return ResourceManager.GetString("viewDateStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczniki daty i czasu.
        /// </summary>
        internal static string viewDateTimeStamps {
            get {
                return ResourceManager.GetString("viewDateTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczniki czasu.
        /// </summary>
        internal static string viewTimeStamps {
            get {
                return ResourceManager.GetString("viewTimeStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Okno.
        /// </summary>
        internal static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer okien.
        /// </summary>
        internal static string windowManager {
            get {
                return ResourceManager.GetString("windowManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kolejność słów.
        /// </summary>
        internal static string wordOrder {
            get {
                return ResourceManager.GetString("wordOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Powiększenie.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
