//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Monitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 64, 0")]
        public global::System.Drawing.Color THM_COL_MonitorChanged {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_MonitorChanged"]));
            }
            set {
                this["THM_COL_MonitorChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DOC_PRJ_RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DOC_PRJ_RecentFiles"]));
            }
            set {
                this["DOC_PRJ_RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color THM_COL_MenuBack {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_MenuBack"]));
            }
            set {
                this["THM_COL_MenuBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color THM_COL_ButtonSelected {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_ButtonSelected"]));
            }
            set {
                this["THM_COL_ButtonSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16, 16, 16")]
        public global::System.Drawing.Color THM_COL_Editor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_Editor"]));
            }
            set {
                this["THM_COL_Editor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color THM_COL_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_ForeColor"]));
            }
            set {
                this["THM_COL_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color THM_COL_BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_BorderColor"]));
            }
            set {
                this["THM_COL_BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color THM_COL_SeperatorColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SeperatorColor"]));
            }
            set {
                this["THM_COL_SeperatorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color THM_COL_SelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SelectedColor"]));
            }
            set {
                this["THM_COL_SelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color THM_COL_ScrollColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_ScrollColor"]));
            }
            set {
                this["THM_COL_ScrollColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color THM_COL_SymbolColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SymbolColor"]));
            }
            set {
                this["THM_COL_SymbolColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brown")]
        public global::System.Drawing.Color THM_COL_StopColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_StopColor"]));
            }
            set {
                this["THM_COL_StopColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool THM_SET_IsDark {
            get {
                return ((bool)(this["THM_SET_IsDark"]));
            }
            set {
                this["THM_SET_IsDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color THM_COL_SeconaryBackColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SeconaryBackColor"]));
            }
            set {
                this["THM_COL_SeconaryBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 192")]
        public global::System.Drawing.Color THM_COL_TerminalForeColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_TerminalForeColor"]));
            }
            set {
                this["THM_COL_TerminalForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color THM_COL_GridLineColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_GridLineColor"]));
            }
            set {
                this["THM_COL_GridLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 23, 23")]
        public global::System.Drawing.Color THM_COL_RowColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_RowColor"]));
            }
            set {
                this["THM_COL_RowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 64, 0")]
        public global::System.Drawing.Color THM_COL_Match {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_Match"]));
            }
            set {
                this["THM_COL_Match"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color THM_COL_Mismatched {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_Mismatched"]));
            }
            set {
                this["THM_COL_Mismatched"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int DEF_INT_BaudRate {
            get {
                return ((int)(this["DEF_INT_BaudRate"]));
            }
            set {
                this["DEF_INT_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 128, 128, 128")]
        public global::System.Drawing.Color THM_COL_TabSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_TabSelectedColor"]));
            }
            set {
                this["THM_COL_TabSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 128, 128, 128")]
        public global::System.Drawing.Color THM_COL_TabSelectedBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_TabSelectedBorderColor"]));
            }
            set {
                this["THM_COL_TabSelectedBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color THM_COL_TabSelectedForeColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_TabSelectedForeColor"]));
            }
            set {
                this["THM_COL_TabSelectedForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color THM_COL_ColumnSeperatorColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_ColumnSeperatorColor"]));
            }
            set {
                this["THM_COL_ColumnSeperatorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color THM_COL_SecondaryForeColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SecondaryForeColor"]));
            }
            set {
                this["THM_COL_SecondaryForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color THM_COL_SelectedShadowColor {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_SelectedShadowColor"]));
            }
            set {
                this["THM_COL_SelectedShadowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 70, 70")]
        public global::System.Drawing.Color THM_COL_ButtonChecked {
            get {
                return ((global::System.Drawing.Color)(this["THM_COL_ButtonChecked"]));
            }
            set {
                this["THM_COL_ButtonChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DEF_INT_DataBits {
            get {
                return ((int)(this["DEF_INT_DataBits"]));
            }
            set {
                this["DEF_INT_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DEF_STR_StopBits {
            get {
                return ((string)(this["DEF_STR_StopBits"]));
            }
            set {
                this["DEF_STR_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string DEF_STR_ParityBit {
            get {
                return ((string)(this["DEF_STR_ParityBit"]));
            }
            set {
                this["DEF_STR_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("frmTxt")]
        public string DEF_STR_InputFormat {
            get {
                return ((string)(this["DEF_STR_InputFormat"]));
            }
            set {
                this["DEF_STR_InputFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("frmTxt")]
        public string DEF_STR_OutputFormat {
            get {
                return ((string)(this["DEF_STR_OutputFormat"]));
            }
            set {
                this["DEF_STR_OutputFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PRG_BOL_AnimateCursor {
            get {
                return ((bool)(this["PRG_BOL_AnimateCursor"]));
            }
            set {
                this["PRG_BOL_AnimateCursor"] = value;
            }
        }
    }
}
